"""add new files

Revision ID: f3269683a08d
Revises: 801830149709
Create Date: 2024-10-09 00:17:45.421640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3269683a08d'
down_revision: Union[str, None] = '801830149709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('departament', sa.String(length=50), nullable=True))
    op.add_column('areas', sa.Column('grade', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'grade')
    op.drop_column('areas', 'departament')
    # ### end Alembic commands ###
